// frontend/src/tabs/IncidentsTab.jsx
//
// Phase-5 Incidents tab. Polls GET /agent/incidents every few seconds so the
// list stays fresh without the user having to refresh. Supports basic
// filtering (status / violation type / zone) and a per-row "Download report"
// button that pulls the PDF generated by /agent/incidents/{id}/report.pdf.
//
// Also exports `RecentIncidentsStrip` — a compact widget used on the Live
// Camera tab to show the last 5 incidents at a glance.
import React, { useEffect, useState, useCallback, useMemo } from "react"
import { API } from "../config"
import { Icon } from "../components/SharedUI"

const POLL_INTERVAL_MS = 4000   // Cheap SQL query, OK to poll briskly.

// ----------------------------------------------------------------------
// Shared helpers
// ----------------------------------------------------------------------

function fetchIncidents({ status = "", violationType = "", zoneId = "", limit = 50 } = {}) {
  const params = new URLSearchParams()
  if (status)        params.set("status", status)
  if (violationType) params.set("violation_type", violationType)
  if (zoneId)        params.set("zone_id", zoneId)
  if (limit)         params.set("limit", String(limit))
  const url = `${API}/agent/incidents${params.toString() ? "?" + params.toString() : ""}`
  return fetch(url).then(r => {
    if (!r.ok) throw new Error(`HTTP ${r.status}`)
    return r.json()
  })
}

function formatRelative(iso) {
  if (!iso) return "—"
  const t  = new Date(iso).getTime()
  const dt = Date.now() - t
  if (dt < 60_000)    return "just now"
  if (dt < 3_600_000) return `${Math.floor(dt / 60_000)}m ago`
  if (dt < 86_400_000) return `${Math.floor(dt / 3_600_000)}h ago`
  return `${Math.floor(dt / 86_400_000)}d ago`
}

function formatLocal(iso) {
  if (!iso) return "—"
  try {
    const d = new Date(iso)
    return d.toLocaleString(undefined, {
      year: "numeric", month: "short", day: "numeric",
      hour: "2-digit", minute: "2-digit",
    })
  } catch { return iso }
}

const SEV_COLOR = { high: "#DC2626", medium: "#D97706", low: "#059669" }
const STATUS_COLOR = { open: "#DC2626", closed: "#059669" }

// ----------------------------------------------------------------------
// RecentIncidentsStrip — compact 5-row strip, collapsible.
//
// The collapse state is persisted to localStorage so the user's choice
// survives across tab switches and reloads.
// ----------------------------------------------------------------------

const STRIP_OPEN_KEY = "recent_incidents_strip_open"

export function RecentIncidentsStrip() {
  // Default closed. We previously defaulted open, but the user prefers a
  // minimal UI by default — explicit click to expand.
  const [open, setOpen] = useState(() => {
    try {
      const v = localStorage.getItem(STRIP_OPEN_KEY)
      return v === "1"
    } catch { return false }
  })
  const [items, setItems]   = useState([])
  const [error, setError]   = useState(null)
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    try { localStorage.setItem(STRIP_OPEN_KEY, open ? "1" : "0") } catch {}
  }, [open])

  // Only poll while the strip is open — no point hitting the API for data
  // the user can't see.
  useEffect(() => {
    if (!open) return
    let cancelled = false
    const tick = () =>
      fetchIncidents({ limit: 5 })
        .then(d => { if (!cancelled) { setItems(d.items || []); setError(null); setLoaded(true) } })
        .catch(e => { if (!cancelled) { setError(e.message); setLoaded(true) } })
    tick()
    const id = setInterval(tick, POLL_INTERVAL_MS)
    return () => { cancelled = true; clearInterval(id) }
  }, [open])

  return (
    <div style={{
      background: "#fff", border: "1px solid #E2E8F0", borderRadius: 10,
      padding: "10px 12px", marginBottom: 12,
    }}>
      <button
        type="button"
        onClick={() => setOpen(o => !o)}
        aria-expanded={open}
        style={{
          display: "flex", alignItems: "center", width: "100%",
          background: "transparent", border: "none", padding: 0,
          cursor: "pointer", color: "#0F172A",
        }}>
        <Icon path="M12 9v2m0 4h.01M5 19h14a2 2 0 001.84-2.75L13.74 4a2 2 0 00-3.48 0L3.16 16.25A2 2 0 005 19z" size={13} color="#475569" />
        <span style={{ marginLeft: 6, fontSize: 12, fontWeight: 600, color: "#1E293B" }}>
          Recent incidents
        </span>
        <span style={{ marginLeft: "auto", fontSize: 11, color: "#94A3B8", display: "inline-flex", alignItems: "center", gap: 6 }}>
          {open
            ? (error ? `polling failed: ${error}` : `last ${items.length || "—"}`)
            : "expand"}
          <Icon
            path={open ? "M19 9l-7 7-7-7" : "M9 5l7 7-7 7"}
            size={11}
            color="#64748B" />
        </span>
      </button>

      {open && (
        loaded
          ? items.length === 0
            ? <div style={{ fontSize: 12, color: "#94A3B8", padding: "8px 0 4px" }}>No incidents yet.</div>
            : (
              <div style={{ display: "flex", flexDirection: "column", gap: 4, marginTop: 8 }}>
                {items.map(inc => (
                  <div key={inc.id} style={{
                    display: "flex", alignItems: "center", gap: 8,
                    fontSize: 12, padding: "4px 0",
                  }}>
                    <span style={{ width: 50, color: "#64748B" }}>#{inc.id}</span>
                    <span style={{
                      flex: 1, fontWeight: 500, color: "#1E293B",
                      whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
                    }}>
                      {inc.violation_type}
                    </span>
                    <span style={{ color: "#64748B", fontSize: 11 }}>
                      {inc.zone_id || "default"}
                    </span>
                    <span style={{
                      fontSize: 10, padding: "2px 6px", borderRadius: 999,
                      background: STATUS_COLOR[inc.status] + "22",
                      color: STATUS_COLOR[inc.status],
                      fontWeight: 600,
                    }}>
                      {inc.status}
                    </span>
                    <span style={{ color: "#94A3B8", fontSize: 11, width: 70, textAlign: "right" }}>
                      {formatRelative(inc.opened_at)}
                    </span>
                  </div>
                ))}
              </div>
            )
          : <div style={{ fontSize: 12, color: "#94A3B8", padding: "8px 0 4px" }}>Loading…</div>
      )}
    </div>
  )
}

// ----------------------------------------------------------------------
// IncidentsBrowser — the actual body (no outer panel wrapper). Lets the
// browser be embedded inside any container; the page-level IncidentsTab
// just wraps this in a det-panel. Used by AgentTab to combine the
// incidents panel + chat in one screen.
// ----------------------------------------------------------------------

export function IncidentsBrowser() {
  const [items, setItems]   = useState([])
  const [error, setError]   = useState(null)
  const [loaded, setLoaded] = useState(false)
  const [statusFilter,    setStatusFilter]    = useState("all") // all | open | closed
  const [typeFilter,      setTypeFilter]      = useState("")     // exact match
  const [zoneFilter,      setZoneFilter]      = useState("")
  const [selectedId,      setSelectedId]      = useState(null)

  const refresh = useCallback(() => {
    fetchIncidents({
      status:        statusFilter === "all" ? "" : statusFilter,
      violationType: typeFilter,
      zoneId:        zoneFilter,
      limit:         100,
    })
      .then(d => { setItems(d.items || []); setError(null); setLoaded(true) })
      .catch(e => { setError(e.message); setLoaded(true) })
  }, [statusFilter, typeFilter, zoneFilter])

  useEffect(() => {
    refresh()
    const id = setInterval(refresh, POLL_INTERVAL_MS)
    return () => clearInterval(id)
  }, [refresh])

  // Derive available type / zone option lists from the visible result set so
  // chips only show values that actually exist in the data.
  const allTypes = useMemo(() => {
    const s = new Set(items.map(i => i.violation_type).filter(Boolean))
    return [...s].sort()
  }, [items])
  const allZones = useMemo(() => {
    const s = new Set(items.map(i => i.zone_id || "default").filter(Boolean))
    return [...s].sort()
  }, [items])

  const openIncidents   = items.filter(i => i.status === "open").length
  const closedIncidents = items.filter(i => i.status === "closed").length

  const downloadReport = (id) => {
    // Trigger native download via a temp anchor — no need for fetch+blob.
    const a = document.createElement("a")
    a.href = `${API}/agent/incidents/${id}/report.pdf`
    a.target = "_blank"
    a.rel = "noopener"
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
  }

  const selected = items.find(i => i.id === selectedId) || null

  return (
    <div>
        {/* Header summary */}
        <div style={{ display: "flex", alignItems: "center", marginBottom: 16, gap: 12, flexWrap: "wrap" }}>
          <span style={{ fontSize: 13, color: "#64748B" }}>
            Showing {items.length} incident{items.length !== 1 ? "s" : ""}
          </span>
          <span style={{
            fontSize: 11, padding: "3px 8px", borderRadius: 999,
            background: "#FEF2F2", color: "#991B1B", fontWeight: 600,
          }}>
            {openIncidents} open
          </span>
          <span style={{
            fontSize: 11, padding: "3px 8px", borderRadius: 999,
            background: "#ECFDF5", color: "#065F46", fontWeight: 600,
          }}>
            {closedIncidents} closed
          </span>
          <button className="btn-outline" style={{ marginLeft: "auto", fontSize: 12, padding: "6px 12px" }} onClick={refresh}>
            <Icon path="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" size={12} color="#374151" />
            Refresh
          </button>
        </div>

        {/* Filter chips */}
        <div style={{ display: "flex", flexWrap: "wrap", gap: 16, marginBottom: 16 }}>
          <FilterGroup label="Status" value={statusFilter} onChange={setStatusFilter}
            options={[["all","All"],["open","Open"],["closed","Closed"]]} />
          <FilterGroup label="Type" value={typeFilter} onChange={setTypeFilter}
            options={[["","All"], ...allTypes.map(t => [t, t])]} />
          <FilterGroup label="Zone" value={zoneFilter} onChange={setZoneFilter}
            options={[["","All"], ...allZones.map(z => [z, z])]} />
        </div>

        {/* Body */}
        {!loaded
          ? <div style={{ padding: "32px 0", color: "#94A3B8", fontSize: 13, textAlign: "center" }}>Loading…</div>
          : error
            ? <div className="alert error"><Icon path="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" size={15} color="#DC2626" />Failed to load incidents: {error}</div>
            : items.length === 0
              ? (
                <div className="empty-state">
                  <div className="empty-icon">
                    <Icon path="M12 9v2m0 4h.01M5 19h14a2 2 0 001.84-2.75L13.74 4a2 2 0 00-3.48 0L3.16 16.25A2 2 0 005 19z" size={22} color="#94A3B8" />
                  </div>
                  <div className="empty-title">No incidents match the current filters</div>
                  <div className="empty-sub">Try widening the status / type / zone filters.</div>
                </div>
              )
              : (
                <div style={{ display: "grid", gridTemplateColumns: selected ? "1fr 1fr" : "1fr", gap: 12 }}>
                  {/* List */}
                  <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                    {items.map(inc => (
                      <IncidentRow
                        key={inc.id}
                        inc={inc}
                        selected={inc.id === selectedId}
                        onSelect={() => setSelectedId(prev => prev === inc.id ? null : inc.id)}
                        onDownload={(e) => { e.stopPropagation(); downloadReport(inc.id) }}
                      />
                    ))}
                  </div>
                  {/* Details panel */}
                  {selected && (
                    <IncidentDetails
                      inc={selected}
                      onClose={() => setSelectedId(null)}
                      onDownload={() => downloadReport(selected.id)}
                    />
                  )}
                </div>
              )
        }
    </div>
  )
}

// Page-level wrapper — keeps the dedicated Incidents nav route working
// (in case anything still links to it) by wrapping the browser in the
// standard det-panel chrome.
export default function IncidentsTab() {
  return (
    <div className="det-panel">
      <div className="det-panel-body">
        <IncidentsBrowser />
      </div>
    </div>
  )
}

// ----------------------------------------------------------------------
// Sub-components
// ----------------------------------------------------------------------

function FilterGroup({ label, value, onChange, options }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
      <span style={{ fontSize: 12, color: "#64748B" }}>{label}:</span>
      <div className="filter-chips">
        {options.map(([v, lbl]) => (
          <button
            key={v}
            className={`filter-chip ${value === v ? "active" : ""}`}
            onClick={() => onChange(v)}>
            {lbl}
          </button>
        ))}
      </div>
    </div>
  )
}

function IncidentRow({ inc, selected, onSelect, onDownload }) {
  const sev    = (inc.severity || "low").toLowerCase()
  const sevC   = SEV_COLOR[sev] || "#64748B"
  const statC  = STATUS_COLOR[inc.status] || "#64748B"
  return (
    <div
      onClick={onSelect}
      style={{
        display: "flex", alignItems: "center", gap: 12,
        padding: "10px 14px", borderRadius: 8,
        background: selected ? "#EFF6FF" : "#F8FAFC",
        border: `1px solid ${selected ? "#BFDBFE" : "#F1F5F9"}`,
        cursor: "pointer", transition: "background 0.1s",
      }}>
      <span style={{ fontSize: 12, fontFamily: "monospace", color: "#64748B", width: 50 }}>
        #{inc.id}
      </span>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 13, fontWeight: 600, color: "#1E293B" }}>
          {inc.violation_type}
        </div>
        <div style={{ fontSize: 11, color: "#94A3B8", marginTop: 2 }}>
          {formatLocal(inc.opened_at)} {"·"} {inc.zone_id || "default"}
        </div>
      </div>
      <span style={{
        fontSize: 10, padding: "2px 6px", borderRadius: 4,
        background: sevC + "22", color: sevC, fontWeight: 600, textTransform: "uppercase",
      }}>
        {sev}
      </span>
      <span style={{
        fontSize: 10, padding: "2px 8px", borderRadius: 999,
        background: statC + "22", color: statC, fontWeight: 600, textTransform: "uppercase",
      }}>
        {inc.status}
      </span>
      <button
        onClick={onDownload}
        title="Download PDF report"
        style={{
          background: "#fff", border: "1px solid #E2E8F0", borderRadius: 6,
          padding: "4px 10px", fontSize: 11, color: "#475569", cursor: "pointer",
          display: "inline-flex", alignItems: "center", gap: 4,
        }}>
        <Icon path="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" size={12} color="#475569" />
        PDF
      </button>
    </div>
  )
}

function IncidentDetails({ inc, onClose, onDownload }) {
  return (
    <div style={{
      background: "#fff", border: "1px solid #E2E8F0", borderRadius: 10,
      padding: 16, height: "fit-content", position: "sticky", top: 16,
    }}>
      <div style={{ display: "flex", alignItems: "center", marginBottom: 12 }}>
        <span style={{ fontSize: 14, fontWeight: 700, color: "#1E293B" }}>
          Incident #{inc.id}
        </span>
        <button
          onClick={onClose}
          style={{
            marginLeft: "auto",
            background: "transparent", border: "none",
            color: "#94A3B8", fontSize: 18, cursor: "pointer", padding: 0,
            lineHeight: 1,
          }}
          aria-label="Close details">
          {"×"}
        </button>
      </div>
      <DetailRow label="Violation" value={inc.violation_type} />
      <DetailRow label="Zone"      value={inc.zone_id || "default"} />
      <DetailRow label="Severity"  value={(inc.severity || "low").toUpperCase()}
        color={SEV_COLOR[(inc.severity || "low").toLowerCase()]} />
      <DetailRow label="Status"    value={(inc.status || "open").toUpperCase()}
        color={STATUS_COLOR[inc.status]} />
      <DetailRow label="Opened"    value={formatLocal(inc.opened_at)} sub={formatRelative(inc.opened_at)} />
      <DetailRow label="Closed"    value={inc.closed_at ? formatLocal(inc.closed_at) : "—"} sub={inc.closed_at ? formatRelative(inc.closed_at) : null} />
      <button
        onClick={onDownload}
        className="btn-primary"
        style={{ marginTop: 12, width: "100%", padding: "8px 12px", fontSize: 13 }}>
        <Icon path="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" size={13} color="#fff" />
        Download PDF report
      </button>
    </div>
  )
}

function DetailRow({ label, value, sub, color }) {
  return (
    <div style={{ marginBottom: 8 }}>
      <div style={{ fontSize: 10, color: "#94A3B8", textTransform: "uppercase", letterSpacing: 0.5 }}>{label}</div>
      <div style={{ fontSize: 13, fontWeight: 600, color: color || "#1E293B", marginTop: 1 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: "#94A3B8", marginTop: 1 }}>{sub}</div>}
    </div>
  )
}
